apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: default
  labels:
    app: user-api
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
          image: docker.io/dk251626910/ffl-user-api-dev:latest
          lifecycle:
            preStop:
              exec:
                command: [ "sh","-c","sleep 5" ]
          ports:
            - containerPort: 50001
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
            - name: varlog
              mountPath: /var/log/filebeat
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: varlog
          hostPath:
            path: /var/log/filebeat
---

apiVersion: v1
kind: Service
metadata:
  name: user-api
  namespace: default
spec:
  ports:
    - port: 50001
  selector:
    app: user-api