// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/acger/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/home",
				Handler: homeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: registerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/profile",
				Handler: profileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/profile/edit",
				Handler: editProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/qiniu/up/token",
				Handler: qiniuUpTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
